### ISSUE TITLE
How would I provide the host's localhost?

### ISSUE THREAD

**Issue by ashramsey** [sernst/locusts#1]
Hey @sernst, I'm trying to provide localhost:3000 as the locust target. I tried using `network_mode: 'host'` in the compose file as well as setting an extra-hosts and aliasing my host machine. But neither approach worked.

Have you tried something like this before? Its purely for testing out the script against my dev application.

Thanks!

**Comment by sernst** [comment]
Hmm, I've found that localhost can be unreliable depending on the network environment. Have you tried `127.0.0.1:3000` to explicitly specify the localhost loopback?
